# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSubRegionMatrixFromSegmentScores <- function(segmentResults, window_size, st, en) {
    .Call('generateSubRegions_getSubRegionMatrixFromSegmentScores', PACKAGE = 'generateSubRegions', segmentResults, window_size, st, en)
}

